apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "app.name" . }}
          image: {{ .Values.image }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
            - name: http-management
              containerPort: {{ .Values.actuatorPort }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.actuatorPort }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.actuatorPort }}
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.actuatorPort }}
            periodSeconds: 5
            failureThreshold: 30
          env:
            - name: SERVER_PORT
              value: "{{ .Values.port }}"
            - name: MANAGEMENT_SERVER_PORT
              value: "{{ .Values.actuatorPort }}"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.otelExporterOTLPEndpoint }}
            - name: OTEL_SERVICE_NAME
              value: {{ include "app.name" . }}
            - name: KUBE_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: pod=$(KUBE_POD_NAME),namespace={{ .Release.Namespace }}
          envFrom:
            - configMapRef:
                name: {{ include "app.name" . }}-properties
            - secretRef:
                name: {{ include "app.name" . }}-db
          {{ if .Values.persistence.enabled }}
          volumeMounts:
            - mountPath: {{ .Values.persistence.mountPath }}
              name: {{ include "app.name" . }}-{{ .Values.persistence.name }}
              readOnly: {{ .Values.persistence.readOnly }}
          {{ end }}
      {{ if .Values.persistence.enabled }}
      volumes:
        - name: {{ include "app.name" . }}-{{ .Values.persistence.name }}
          persistentVolumeClaim:
            claimName: {{ include "app.name" . }}-{{ .Values.persistence.name }}-pvc
      {{ end }}