{{ if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app.name" . }}-{{ .Values.persistence.name }}-pvc
spec:
  storageClassName: {{ include "app.name" . }}-{{ .Values.persistence.name }}-sc
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.storage }}
{{ end }}