apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.servicename" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    {{- with .Values.prometheus.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: http-management
      port: 8081
      targetPort: http-management
      protocol: TCP
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
